In [1]:
import pandas as pd

compare

In [8]:
shop_7sep={
    "fruits":['mango','apple','banana','papaya'],
    "price":[100,150,60,30],
    "qunt":[10,8,12,14]}
stock_7sep=pd.DataFrame(shop_7sep)
shop_8sep={
    "fruits":['mango','apple','banana','papaya'],
    "price":[120,200,60,35],
    "qunt":[15,6,24,17]}
stock_8sep=pd.DataFrame(shop_8sep)
    #compare
stock_7sep.compare(stock_8sep)
stock_7sep.compare(stock_8sep,align_axis=0)
stock_7sep.compare(stock_8sep,keep_shape=True)
stock_7sep.compare(stock_8sep,keep_equal=True)
stock_7sep.compare(stock_8sep,align_axis=0,keep_shape=True,keep_equal=True)

         fruits  price  qunt
0 self    mango    100    10
  other   mango    120    15
1 self    apple    150     8
  other   apple    200     6
2 self   banana     60    12
  other  banana     60    24
3 self   papaya     30    14
  other  papaya     35    17

pivoting

In [ ]:
monthly_sales={
    "product":['laptop','mobile','laptop','mobile','laptop','laptop'],
    "month":['jan','jan','feb','feb','mar','apr'],
    "price":[95000,25000,67000,12000,65000,75000]
}
sales=pd.DataFrame(monthly_sales)
sales
#pivot
sales.pivot(
    columns="month",
    index="product",
    values="price"
)

month        apr      feb      jan      mar
product
laptop   75000.0  67000.0  95000.0  65000.0
mobile       NaN  12000.0  25000.0      NaN

In [8]:
monthly_sales={
    "product":['laptop','mobile','laptop','mobile','laptop','laptop','mobile'],
    "month":['jan','jan','feb','feb','mar','mar','feb'],
    "price":[95000,25000,67000,12000,65000,75000,10000]
}
sales=pd.DataFrame(monthly_sales)
sales
#pivot_table
sales.pivot_table(
    columns="month",
    index="product",
    values="price",
    aggfunc='sum'
)

month        feb      jan       mar
product
laptop   67000.0  95000.0  140000.0
mobile   22000.0  25000.0       NaN

melting

In [10]:
shop_sales={
    "product":['laptop','mobile','mouse'],
    "jan":[45000,14000,140],
    "feb":[65000,25000,560],
    "mar":[75000,23000,750]
}
sales_df=pd.DataFrame(shop_sales)
sales_df.melt(id_vars="product",var_name="month",value_name="price")

  product month  price
0  laptop   jan  45000
1  mobile   jan  14000
2   mouse   jan    140
3  laptop   feb  65000
4  mobile   feb  25000
5   mouse   feb    560
6  laptop   mar  75000
7  mobile   mar  23000
8   mouse   mar    750