## creation of data frames,exploring data

In [1]:
import pandas as pd

## data frames

In [3]:
student={
    'id':['s2601','s2602','s2603','s2604'],
    'name':['safa','poojashree','rakshitha','rajiya'],
    'age':[19,20,17,21]
}
#creation of dataframe
df=pd.DataFrame(student)
df

      id        name  age
0  s2601        safa   19
1  s2602  poojashree   20
2  s2603   rakshitha   17
3  s2604      rajiya   21

In [4]:
#shape
df.shape
#size
df.size
#columns
df.columns
#rename
df.rename(columns={"id":"student_id"})#temporary rename
df.rename(columns={"id":"student_id"},inplace=True)#permanent

In [12]:
df

  student_id        name  age
0      s2601        safa   19
1      s2602  poojashree   20
2      s2603   rakshitha   17
3      s2604      rajiya   21

export to csv file

In [5]:
df.to_csv("std_data.csv")
df.to_csv("std2_data.csv",index=False)

import csv file

In [6]:
#same folder
df=pd.read_csv("companydemo.csv")
df
#diff folder
df1=pd.read_csv("C:/Users/poojashree/OneDrive/Desktop/Placement/pandas/subdata_pandas/student.csv")
df1

    id             name  age  marks   fees
0  101    Akshay Shetty   20     85  25000
1  102       Ananya Rao   21     92  30000
2  103   Rohit Bhandary   19     76  28000
3  104    Nisha D'Souza   20     88  25000
4  105  Karthik Poojary   22     69  32000
5  106    Shreya Shetty   19     95  30000
6  107       Rohan Naik   21     72  27000
7  108     Deepika Bhat   20     81  28000
8  109  Abhishek Kotian   22     64  26000
9  110        Pooja Rai   19     90  30000

import excel file

In [7]:
df=pd.read_excel("C:/Users/poojashree/OneDrive/Desktop/Placement/pandas/subdata_pandas/expense.xlsx")
df

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

exploring data

In [8]:
df=pd.read_csv("subdata_pandas/employee.csv")
df

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [9]:
#top 10 rows
df.head(10)

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
5,6,Male,22-08-1958,15,Sales,32100,13500,8.17,5.58,No
6,7,Male,26-04-1956,15,IT,36000,18750,8.17,9.50,No
7,8,Female,06-05-1966,12,Finance,21900,9750,8.17,NaN,No
8,9,Female,23-01-1946,15,Accounting,27900,12750,8.17,9.58,No
9,10,Female,13-02-1946,12,Finance,24000,13500,8.17,20.33,No

In [10]:
#last 10 rows
df.tail(10)

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
464,465,Male,20-07-1962,12,Engineering,33900,16500,5.33,8.83,No
465,466,Female,15-06-1948,12,Engineering,23400,13500,5.33,16.50,No
466,467,Female,18-08-1967,16,IT,32850,19500,5.33,1.67,No
467,468,Female,28-11-1965,16,Engineering,55750,19980,5.33,3.00,No
468,469,Female,01-06-1964,15,Accounting,25200,13950,5.33,4.75,No
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [11]:
#shape
df.shape
#size
df.size
#info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   474 non-null    int64
 1   gender               474 non-null    str
 2   dateofbirth          473 non-null    str
 3   education            474 non-null    int64
 4   department           474 non-null    str
 5   salary               474 non-null    int64
 6   starting_salary      474 non-null    int64
 7   job_time             474 non-null    float64
 8   previous_experience  449 non-null    float64
 9   minority             471 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 37.2 KB

In [12]:
#describe
df.describe()

,id,education,salary,starting_salary,job_time,previous_experience
count,474.000000,474.000000,474.000000,474.000000,474.000000,449.000000
mean,237.500000,14.609705,34419.567511,17016.086498,6.759072,8.406682
std,136.976275,2.442919,17075.661465,7870.638154,0.838523,8.750270
min,1.000000,12.000000,15750.000000,9000.000000,5.250000,0.170000
25%,119.250000,12.000000,24000.000000,12487.500000,6.000000,2.000000
50%,237.500000,15.000000,28875.000000,15000.000000,6.750000,4.920000
75%,355.750000,16.000000,36937.500000,17490.000000,7.500000,12.000000
max,474.000000,21.000000,135000.000000,79980.000000,8.170000,39.670000